#python api server stuff
FROM python:3.10-slim

#set the  working directory
WORKDIR /app

#read req
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY src/ ./src/
COPY data/ ./data/

# Expose port 5001
EXPOSE 5001


#  run the API server
CMD ["python", "-m", "src.api"]

