name: Debug Mad Branch Test

on:
  push:
    branches: [ debug_mad ]
  pull_request:
    branches: [ debug_mad ]
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'cloud-integration'
        type: choice
        options:
        - cloud-integration
        - unit-tests
        - api-tests
        - all

jobs:
  debug-mad-cloud-test:
    runs-on: ubuntu-latest
    if: github.event.inputs.test_type == 'cloud-integration' || github.event.inputs.test_type == 'all' || github.event_name == 'push' || github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Make scripts executable
      run: |
        chmod +x scripts/*.sh
        chmod +x docker/*.sh
    
    - name: Run Cloud Integration Tests
      run: |
        echo "Running cloud integration tests for debug_mad branch..."
        if [ -f "docker/run-cloud-tests.sh" ]; then
          ./docker/run-cloud-tests.sh
        elif [ -f "docker-compose.test.yml" ]; then
          docker compose -f docker-compose.test.yml up --build --abort-on-container-exit
        else
          echo "No cloud test script found"
          exit 1
        fi
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: debug-mad-test-results
        path: test-results/
    
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Debug Mad Branch Test Results
        path: test-results/results.xml
        reporter: java-junit

  debug-mad-unit-test:
    runs-on: ubuntu-latest
    if: github.event.inputs.test_type == 'unit-tests' || github.event.inputs.test_type == 'all'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-cloud.txt
    
    - name: Run unit tests
      run: |
        echo "Running unit tests for debug_mad branch..."
        pytest tests/test_data_processor.py -v

  debug-mad-api-test:
    runs-on: ubuntu-latest
    if: github.event.inputs.test_type == 'api-tests' || github.event.inputs.test_type == 'all'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-cloud.txt
    
    - name: Run API tests
      run: |
        echo "Running API tests for debug_mad branch..."
        pytest tests/test_api.py -v

  debug-mad-summary:
    runs-on: ubuntu-latest
    needs: [debug-mad-cloud-test, debug-mad-unit-test, debug-mad-api-test]
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Summary
      run: |
        echo "🎉 Debug Mad Branch Test Summary"
        echo "Branch: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"
        echo "Triggered by: ${{ github.event_name }}"
        if [ "${{ github.event.inputs.test_type }}" != "" ]; then
          echo "Test type: ${{ github.event.inputs.test_type }}"
        fi
        echo "All tests completed for debug_mad branch!"